import type { NextPage } from "next";
import dynamic from "next/dynamic";
import Head from "next/head";

const Test = dynamic(() => import("../components/test"), {
  ssr: false,
});

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-full justify-center items-center">
        <div>
          <div className="m-4"></div>
          <div>
            <Test src={"./img1.jpg"} />
          </div>
          <div>
            <Test src={"./img2.jpg"} />
          </div>
          <div>
            <Test src={"./img3.jpg"} />
          </div>
          <div>
            <Test src={"./img4.jpg"} />
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
