import type { NextPage } from "next";
import dynamic from "next/dynamic";
import Head from "next/head";
import Image from "next/image";
import { Blurhash } from "react-blurhash";

const Test = dynamic(() => import("../components/test"), {
  ssr: false,
});

const serverHash = "U9GIY:ISwhMv*GJDD6E3?tyEDOtS?ZW@8{Rk";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-full justify-center items-center">
        <div>
          <div className="m-4">Browser hash generation is slow</div>
          <div>
            <Test src={"./img1.jpg"} />
          </div>
          <div className="m-4">
            <div>Generated on the server:</div>
            <div>{serverHash}</div>
          </div>
          <div className="m-4">
            <Blurhash
              hash={serverHash}
              resolutionX={32}
              resolutionY={32}
              punch={1}
              width={240}
              height={204}
            />
          </div>
          <div className="m-4">
            <Image src="/limecat.jpg" alt="Lime cat" width={240} height={204} />
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
